### ISSUE TITLE
Task List for 7 December

### ISSUE THREAD

**Issue by ebeshero** [AliceR98/DIGIT-110-AJC-Survey#4]
- [ ] Add project info and and background on AJC  @san5281 

- [ ] Stylize ins? Maybe it's okay?

- [ ] Stylize the special table at the top of the survey differently from the tables in the survey @san5281 

```css
section#table table { }

table { }
```
